export const SEARCH_CHANGE = 'SEARCH_CHANGE';
export const ARTIST_SEARCH_SUCCESS = 'ARTIST_SEARCH_SUCCESS';
export const ALBUM_SEARCH_SUCCESS = 'ALBUM_SEARCH_SUCCESS';
export const ARTIST_LOAD_SUCCESS = 'ARTIST_LOAD_SUCCESS';
export const ALBUM_LOAD_SUCCESS = 'ALBUM_LOAD_SUCCESS';
